name: 'Check Cyclomatic Complexity'
description: 'Analyze go source files for cyclomatic complexity'
inputs:
  working_directory:
    required: true
    description: 'The directory to run the analysis in'
    default: './'
runs:
  using: 'docker'
  image: 'Dockerfile'